# Generated by Django 4.2.4 on 2023-08-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=999)),
                ("descricao", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=999, max_digits=999)),
            ],
            options={
                "verbose_name": "Calca",
                "verbose_name_plural": "Calcas",
            },
        ),
        migrations.CreateModel(
            name="Camiseta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=999)),
                ("descricao", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=999, max_digits=999)),
            ],
            options={
                "verbose_name": "Camiseta",
                "verbose_name_plural": "Camisetas",
            },
        ),
        migrations.CreateModel(
            name="Chapeu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=999)),
                ("descricao", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=999, max_digits=999)),
            ],
            options={
                "verbose_name": "Chapeu",
                "verbose_name_plural": "Chapeus",
            },
        ),
        migrations.CreateModel(
            name="Tenis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=999)),
                ("descricao", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=999, max_digits=999)),
            ],
            options={
                "verbose_name": "Tenis",
                "verbose_name_plural": "Tenis",
            },
        ),
    ]
