# Generated by Django 4.2.4 on 2023-08-23 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("backgeek", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Calca",
        ),
        migrations.DeleteModel(
            name="Chapeu",
        ),
        migrations.DeleteModel(
            name="Tenis",
        ),
        migrations.AddField(
            model_name="camiseta",
            name="capa",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="uploader.image",
            ),
        ),
        migrations.AlterField(
            model_name="camiseta",
            name="preco",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
    ]
