# Generated by Django 4.2.4 on 2023-08-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("backgeek", "0002_delete_calca_delete_chapeu_delete_tenis_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camiseta",
            name="capa",
        ),
        migrations.AddField(
            model_name="camiseta",
            name="capa",
            field=models.ManyToManyField(related_name="Camiseta", to="uploader.image"),
        ),
    ]
