# Generated by Django 4.2.4 on 2023-08-23 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backgeek", "0003_remove_camiseta_capa_camiseta_capa"),
    ]

    operations = [
        migrations.RenameField(
            model_name="camiseta",
            old_name="capa",
            new_name="imagem",
        ),
    ]
