# Generated by Django 4.2.4 on 2023-09-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('backgeek', '0005_alter_camiseta_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='imagem',
            field=models.ManyToManyField(blank=True, related_name='Camiseta', to='uploader.image'),
        ),
    ]
