# Generated by Django 4.2.5 on 2023-09-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("backgeek", "0007_alter_camiseta_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estampa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Moletom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=999)),
                ("descricao", models.CharField(max_length=100)),
                (
                    "preco",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=7, null=True
                    ),
                ),
                (
                    "imagem",
                    models.ManyToManyField(related_name="Moletom", to="uploader.image"),
                ),
            ],
            options={
                "verbose_name": "Moletom",
                "verbose_name_plural": "Moletons",
            },
        ),
    ]
