# Generated by Django 4.2.5 on 2023-12-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backgeek", "0008_estampa_moletom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=999)),
                ("descricao", models.CharField(max_length=100)),
                (
                    "preco",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=7, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Moletom",
                "verbose_name_plural": "Moletons",
            },
        ),
    ]
