# Generated by Django 4.2.5 on 2023-12-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backgeek", "0009_produto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=122)),
            ],
        ),
        migrations.AlterModelOptions(
            name="produto",
            options={"verbose_name": "Produto", "verbose_name_plural": "Produtos"},
        ),
    ]
