# Generated by Django 4.2.5 on 2023-12-05 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backgeek", "0010_categoria_alter_produto_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="Categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livros",
                to="backgeek.categoria",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categoria",
            name="titulo",
            field=models.CharField(max_length=100),
        ),
    ]
