# Generated by Django 4.2.5 on 2023-12-05 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backgeek", "0011_produto_categoria_alter_categoria_titulo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produto",
            old_name="Categoria",
            new_name="categoria",
        ),
    ]
