# Generated by Django 4.2.5 on 2023-12-05 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("backgeek", "0012_rename_categoria_produto_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="capa",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="uploader.image",
            ),
        ),
    ]
